### ISSUE TITLE
New mde containers start fails with "exec: \"/config/initSiebel\": permission denied"

### ISSUE THREAD

**Issue by steveurkel123** [OracleSiebel/ConfiguringSiebel#104]
Hi Duncan,

first of all thank you very much for your effort here.

I was trying out the new build process with mde. I got through more or less until I started the containers when I encountered the issue:

`starting container process caused "exec: \"/config/initSiebel\": permission denied"`

I could solve this issue and would like to let you know.

I amended Containerization/Docker/oraclelinux/classic-mde/build/persistence/siebel/dockerfile with line

`RUN ["chmod", "+x", "config/initSiebel"]`

in below code part

> HEALTHCHECK     --interval=30s \
>                 --timeout=10s \
>                 --retries=3 \
>                 --start-period=30s \
>                 CMD bash /config/healthcheck
> VOLUME ["/persistent"]
> VOLUME ["/sfs"]
> RUN ["chmod", "+x", "config/initSiebel"]
> ENTRYPOINT [ "/config/initSiebel" ]

After that the containers started without issue.

Can you confirm this and in case update the file?

Best regards

**Comment by OracleSiebel** [comment]
Hi Steve,

Thanks very much for reporting this. My guess is that I didn't encounter this due to the fact that the executable flag is on the file before the build starts. I'd prefer to solve this by using bash to run the init script rather than running chmod during the build. It just feels a little cleaner, but ultimately it amounts to the same thing.

Good to hear you're able to get everything up and running though.

**Comment by OracleSiebel** [comment]
Resolved in https://github.com/OracleSiebel/ConfiguringSiebel/commit/ab663b55aeab9ecd09c6057b0868c474aecaa62e
