### ISSUE TITLE
List Applets are not rendering after implementing solution Open UI Double Click

### ISSUE THREAD

**Issue by rajeshcse234** [OracleSiebel/ConfiguringSiebel#26]
Hi Team,

we have implemented this change in our development environment , after these changes none of the list applets are showing in our application.
we don;t see any error in console of the browser too.
Please suggest.

Regards
Rajesh

**Comment by OracleSiebel** [comment]
Most likely reason is that you didn't copy the code exactly, or name the files with the right case (upper and lower). Please double check that first.

**Comment by duncanford** [comment]
To add to the previous comment, if you are using IP16.8 and above, your can revert to seeded manifest content using a command line switch for a thick client in order to log into Siebel and rectify content in the manifest UI list applets - https://blogs.oracle.com/siebelcrm/restricting-manifest-load-to-seeded-records.

**Comment by rajeshcse234** [comment]
issue is resolved now thanks
File name was in lower case ...

**Comment by duncanford** [comment]
Thanks for taking the time to confirm the fix.
