### ISSUE TITLE
Java Nullpointer exception on SES installation

### ISSUE THREAD

**Issue by wildtangent** [OracleSiebel/ConfiguringSiebel#47]
I am getting the following error when trying to build the SES container. 

```
Installing Siebel ...
Starting Oracle Universal Installer...

Preparing to launch Oracle Universal Installer from /tmp/OraInstall2018-11-12_11-21-47AM. Please wait ...

===================================================


java.lang.NullPointerException
	at com.oracle.siebel.apiinstaller.InstallerUtility.loadResponseFile(InstallerUtility.java:438)
	at oracle.sysman.oio.oioc.OiocOneClickInstaller.main(OiocOneClickInstaller.java:306)
```

The other 2 images complete without any errors. I am attempting to install Siebel 15.x

**Comment by OracleSiebel** [comment]
You say that the other two images complete without error, but this leaves me confused as there is no SAI to be installed for IP15.

As mentioned in the other issue, I would probably start by generating a clean IP15 installer response file manually by running an install for IP15 manually. There could be a very different set of response parameters for that version.

**Comment by OracleSiebel** [comment]
Closing this issue as it pertains to a Siebel release earlier than IP17, against which the content here was never tested.

**Comment by RyabykinIlya** [comment]
@OracleSiebel The same issue for ip21.5 installer (sai component)

**Comment by OracleSiebel** [comment]
Usually, the null-pointer error indicates that there's a missing entry in the resp file. I haven't pushed to Github for a while. Are you able to create an rsp file for SAI from a standard install and put that in place of the sai.resp file?

**Comment by RyabykinIlya** [comment]
> Usually, the null-pointer error indicates that there's a missing entry in the resp file. I haven't pushed to Github for a while. Are you able to create an rsp file for SAI from a standard install and put that in place of the sai.resp file?

Yes, of course. ip21 have completely different response file for installation.
Moreover, there is not way to install sai separately from another components (as I has been realized from docs.oracle.com "new installation" instruction)

Could you answer if you plan to update the instructions for installing newer versions in containers?

**Comment by OracleSiebel** [comment]
It won't be completely different. It'll be one setting.

The currently provided installers will work all the way to the point of the Tomcat change in 21.4. So if you need to install 21.2, 21.3 or 21.4, you can do that using the MDE folder:

https://github.com/OracleSiebel/ConfiguringSiebel/tree/master/Containerization/Docker/oraclelinux/classic-mde

You'll find that these now install everything to a single container which is activated with a given containerMode. Though the container looks bigger than the previous SAI container, the total on-disk size for CGW, SAI, and SES together is less now that we have a single SIEBEL container.

I do plan to update for 21.4 and beyond, but I'll probably create a new repository before doing so in order to be able to preserve each version in separate releases. There's far more change for the containers than for the other things housed in this repository. If I overwrite content here, people wanting to install 21.2 to 21.4 will be unable to proceed. None of this will happen until at least the week after next.

If you're desperate to move forward sooner than that, please email me @ duncan-dot-ford-at-oracle-dot-com.
