### ISSUE TITLE
Tag oraclelinux:latest for 32bit client dockerfile not working anymore

### ISSUE THREAD

**Issue by steveurkel123** [OracleSiebel/ConfiguringSiebel#93]
Hi,

the tag oraclelinux:latest in Containerization/Docker/ol7/build/32-bit_instantclient_12c/dockerfile

`FROM oraclelinux:latest`

doesn't seem to work anymore. When I used 

`FROM oraclelinux:8.2`

it worked again. Maybe a hint should be added to instructions to check on https://hub.docker.com/_/oraclelinux?tab=tags for latest tag.

Regards

**Comment by OracleSiebel** [comment]
Hi,

You're absolutely right. By way of explanation, this isn't a 'supported' channel, and the intention is to give you a good head start rather than provide something right up to date.

I'm pretty sure that 8.2 will not work, so you might want to try 7-slim or 7 instead. I'll be happy to help you until you get a working build. Alternatively, you can access our pre-built containers by entering a support request. That's only going to be of use however if an ENU-only build will work for you.

Thanks for taking the time to report this as I'm sure it'll help others.

**Comment by OracleSiebel** [comment]
Hi. I had a think about this and realised it might be more trouble than I initially though, so I've gone through the rework and pushed an update. You should pull the latest repository content and then you're build should go well. As suggested, this now uses oraclelinux:7-slim. I've tested this with 20.8 through to a Call Center login. Hope this helps.
